# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'VCSwiftToolkit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VCSwiftToolkit

  target 'VCSwiftToolkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
